---
apiVersion: v1
kind: Namespace
metadata:
  name: personal-site
  labels:
    app.kubernetes.io/name: personal-site
    app.kubernetes.io/part-of: personal-site
    app.kubernetes.io/managed-by: argocd
  annotations:
    app.kubernetes.io/description: "Personal landing page namespace"

