---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: personal-site-tunnel-credentials
  namespace: personal-site
  labels:
    app.kubernetes.io/name: personal-site
    app.kubernetes.io/part-of: personal-site
    app.kubernetes.io/component: tunnel
    app.kubernetes.io/managed-by: argocd
spec:
  encryptedData:
    credentials.json: AgBDt745fBv8lIXi/LyIUDmcgbD1jSeZvfo+Cw56b6rO4QQ/ot575Q34YFjj2v6twZh1WBBfM3xg4dG3tdaRVqF1bj++Qc3bKl0rr4CNfEAM5QtQ+6lEgtPD3kgA4wKjmRpRqOwNHNmWqKLdWKf9cxji3L/ARl58oBD32+zhgpArzc+whhGBlrm7HX/S+U5C56OmgI6+9g9bVnwzJDNrd8Rq/gCjmWXerswvh1Pz+tSSGTauy3GaqmzXaAWI2VBQ24ZNf0oHlr4FVYfgJ7fuhcLmD97DfGRPPkKOqFQCohLVsOfWMNvyPhhh23zM0SMPPcvmd5JE0FpIlzvcF2AnDu3d8A4qMquRwrmJOYGWGr8W6sTRZzuRq6vtq+c+Vbllq0NsjPT3IrkVScMXI7b8aReNBfpRNmokS3I769t5z01emg0r0iAm1kYB8/2Y5zWzMriQXveDkqaEmVGNmHdVlJflfdfWrNuvpB2psF6Oqblrgz3uwLnH9L1uYat8V8nKSWT2BDEtTirsZUphWjul/VJ3cn7wNKMEOrUqrcJSIXswxvy8mLVedhfUZxH7QBIuYa9nE7knoZWQR9tulPFlaxyK52VjZN2SxLocNAmT1c0crANK6h62P3n7wHCyy4xczl22YZoVl6EVvjq66Z4t3LFjwSnW/GlRhCBv8eZzdPFMMqIWW+iv9mfyujrT5Iaysn4waiaggECOy1yzCxGhg/ibLEk+oPrxzlFfuaku0WCKh8PU2kHt3UL6mOzR+hy39lNCjSLAX2hnNFuyOVLqOsKB9YqMZ064nMkMTs1M8ZvTlQu3cN086GcjEhFJ3NPGBV85e4kkTyNVr/Gw+GGiJBlNajuRYgFdr+1Y9UF/T9UvKxSe/KhDYxUPfd08g0WglJpDPMVvu6PM1kPvwKn8Un2iebA35mwRfq0YWbjMphSk
  template:
    metadata:
      name: personal-site-tunnel-credentials
      namespace: personal-site
      labels:
        app.kubernetes.io/name: personal-site
        app.kubernetes.io/part-of: personal-site
        app.kubernetes.io/component: tunnel
        app.kubernetes.io/managed-by: argocd
    type: Opaque
